# Generated by Django 4.1.6 on 2024-04-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookcopy",
            options={
                "verbose_name": "Экземпляр книги",
                "verbose_name_plural": "Экземпляры книг",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(to="books.author"),
        ),
    ]
