# Generated by Django 4.1.6 on 2024-04-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_bookcopy_options_book_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
